server:
  port: 8080

spring:
  datasource:
    username: user
    password: 123456
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
          batch_versioned_data: true
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
logging:
  level:
    org:
      springframework:
        cache: DEBUG
      hibernate:
        orm:
          jdbc:
            query: OFF
            bind: OFF
        SQL: OFF
        type:
          descriptor:
            sql:
              BasicBinder: OFF
  file:
    name: logs/myapp.log
    max-size: 10MB
    max-history: 10
indexing-settings:
  sites:
#    - url: https://www.playback.ru/
#      name: PlayBack.Ru
#    - url: https://volochek.life/
#      name: Volochek.Life
#    - url: https://radiomv.ru/
#      name: Милицейская волна
#    - url: https://ipfran.ru/
#      name: ИПФ РАН
    - url: https://dimonvideo.ru/
      name: DimonVideo

jsoup-settings:
  timeout: 10000
  intervals:
    - 1000
    - 1500
    - 2000
    - 2500
    - 3000
    - 3500
    - 4000
  followRedirect: false
  ignoreHTTPErrors: true
  userAgents:
    - Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.59
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
  referrer: https://www.google.com


